export const FETCH_USERINFO = "FETCH_USERINFO";
export const FETCH_USERINFO_SUCCESS = "FETCH_USERINFO_SUCCESS";
export const FETCH_USERINFO_FAILURE = "FETCH_USERINFO_FAILURE";

export const SET_SELECTED_USER = "SET_SELECTED_USER";
